################################################################################
#   Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved
#
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
################################################################################

  # Carbon Configuration Parameters
wso2.carbon:
    # value to uniquely identify a server
  id: siddhi-runner
    # server name
  name: Siddhi Runner Distribution
    # ports used by this server
  ports:
      # port offset
    offset: 0

transports:
  http:
    listenerConfigurations:
      -
        id: "default"
        host: "0.0.0.0"
        port: 9090
      -
        id: "msf4j-https"
        host: "0.0.0.0"
        port: 9443
        scheme: https
        sslConfig:
          keyStore: "${carbon.home}/resources/security/wso2carbon.jks"
          keyStorePass: wso2carbon
          certPass: wso2carbon

    transportProperties:
      -
        name: "server.bootstrap.socket.timeout"
        value: 60
      -
        name: "client.bootstrap.socket.timeout"
        value: 60
      -
        name: "latency.metrics.enabled"
        value: true


  # Datasource Configurations
dataSources:
  - name: WSO2_PERMISSIONS_DB
    description: The datasource runner used for permission feature
    jndiConfig:
      name: jdbc/PERMISSION_DB
      useJndiReference: true
    definition:
      type: RDBMS
      configuration:
        jdbcUrl: 'jdbc:h2:${sys:carbon.home}/wso2/${sys:wso2.runtime}/database/PERMISSION_DB;IFEXISTS=TRUE;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000;MVCC=TRUE'
        username: wso2carbon
        password: wso2carbon
        driverClassName: org.h2.Driver
        maxPoolSize: 10
        idleTimeout: 60000
        connectionTestQuery: SELECT 1
        validationTimeout: 30000
        isAutoCommit: false
